### ISSUE TITLE
Use Optionals

### ISSUE THREAD

**Issue by hmksq** [Flibio/MinigameCore#3]
Return Optional instead of returning booleans or integers directly.

**Comment by Flibio** [comment]
**Thanks for the suggestion**, but I have a quick question: 
Why should I use optionals for booleans and integers that will never be null?

**Comment by hmksq** [comment]
I thought about that too, but they use optionals everywhere in SpongeAPI right?
I think it is a good standard to follow.

**Comment by Flibio** [comment]
I don't think that it is necessary for things that will always have a value. I believe that optionals are to stop NPEs. I agree with the fact it is a good standard to follow, so I will be sure to use optionals whenever there is a possibility that the object is not available.
